-- ============================================================================
-- SOA Database Adapter Pattern - Database Schema
-- Schema: LENDWISE
-- Connection JNDI: eis/DB/LendWiseDS
-- ============================================================================

-- Create Schema
CREATE USER LENDWISE IDENTIFIED BY lendwise_pwd
    DEFAULT TABLESPACE users
    QUOTA UNLIMITED ON users;

GRANT CONNECT TO LENDWISE;
-- GRANT RESOURCE TO LENDWISE;  -- Commented: RESOURCE not in PL/SQL grammar

-- Switch to LENDWISE schema
ALTER SESSION SET CURRENT_SCHEMA = LENDWISE;

-- ============================================================================
-- Table: BORROWERS (BorrowerDB.Borrower)
-- ============================================================================
CREATE TABLE BORROWERS (
    BORROWER_ID         NUMBER(19) PRIMARY KEY,
    SSN                 VARCHAR2(11) NOT NULL UNIQUE,
    NAME                VARCHAR2(200) NOT NULL,
    CREDIT_SCORE        NUMBER(3),
    MONTHLY_INCOME      NUMBER(15,2) NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE BORROWER_SEQ START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_BORROWERS_SSN ON BORROWERS(SSN);

COMMENT ON TABLE BORROWERS IS 'Borrower information - linked via BorrowerDB.jca adapter';
COMMENT ON COLUMN BORROWERS.BORROWER_ID IS 'Primary key - populated from BORROWER_SEQ';
COMMENT ON COLUMN BORROWERS.SSN IS 'Social Security Number - used for selectBorrowerBySSN operation';
COMMENT ON COLUMN BORROWERS.CREDIT_SCORE IS 'Credit score (300-850) - updated via updateBorrowerCredit operation';

-- ============================================================================
-- Table: LOAN_APPLICATIONS (LoanDB.LoanApplication)
-- ============================================================================
CREATE TABLE LOAN_APPLICATIONS (
    LOAN_ID             VARCHAR2(50) PRIMARY KEY,
    BORROWER_ID         NUMBER(19) NOT NULL REFERENCES BORROWERS(BORROWER_ID),
    LOAN_AMOUNT         NUMBER(15,2) NOT NULL,
    PROPERTY_VALUE      NUMBER(15,2) NOT NULL,
    PROPERTY_ADDRESS    VARCHAR2(500),
    LTV_RATIO           NUMBER(5,2),
    STATUS              VARCHAR2(50) DEFAULT 'PENDING',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_LOANS_BORROWER ON LOAN_APPLICATIONS(BORROWER_ID);
CREATE INDEX IDX_LOANS_STATUS ON LOAN_APPLICATIONS(STATUS);

COMMENT ON TABLE LOAN_APPLICATIONS IS 'Loan application records - linked via LoanDB.jca adapter';
COMMENT ON COLUMN LOAN_APPLICATIONS.LOAN_ID IS 'Primary key - UUID generated by BPEL process';
COMMENT ON COLUMN LOAN_APPLICATIONS.LTV_RATIO IS 'Loan-to-Value ratio - calculated by LOAN_PKG.CALCULATE_LTV';
COMMENT ON COLUMN LOAN_APPLICATIONS.STATUS IS 'Application status: PENDING, APPROVED, REJECTED, MANUAL_REVIEW';

-- ============================================================================
-- Table: LOAN_DECISIONS (DecisionDB.LoanDecision)
-- ============================================================================
CREATE TABLE LOAN_DECISIONS (
    DECISION_ID         VARCHAR2(50) PRIMARY KEY,
    LOAN_ID             VARCHAR2(50) NOT NULL REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    DECISION            VARCHAR2(50) NOT NULL,
    RISK_SCORE          NUMBER(4),
    NOTES               VARCHAR2(2000),
    REVIEWED_BY         VARCHAR2(100),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_DECISIONS_LOAN ON LOAN_DECISIONS(LOAN_ID);
CREATE INDEX IDX_DECISIONS_DECISION ON LOAN_DECISIONS(DECISION);

COMMENT ON TABLE LOAN_DECISIONS IS 'Loan decision audit trail - linked via DecisionDB.jca adapter';
COMMENT ON COLUMN LOAN_DECISIONS.DECISION IS 'Decision result: APPROVED, REJECTED, MANUAL_REVIEW';
COMMENT ON COLUMN LOAN_DECISIONS.RISK_SCORE IS 'Risk score (0-1000) - calculated by DECISION_PKG.RUN_RISK_ASSESSMENT';
COMMENT ON COLUMN LOAN_DECISIONS.REVIEWED_BY IS 'Reviewer ID for manual decisions';

-- ============================================================================
-- Package: LOAN_PKG (LoanDB.calculateLTV stored procedure)
-- ============================================================================
CREATE OR REPLACE PACKAGE LOAN_PKG AS
    -- Calculate Loan-to-Value ratio
    -- Called by: LoanDB.jca - operation="calculateLTV"
    -- InteractionSpec: oracle.tip.adapter.db.DBStoredProcedureInteractionSpec
    PROCEDURE CALCULATE_LTV(
        p_loan_amount    IN  NUMBER,
        p_property_value IN  NUMBER,
        p_ltv_ratio      OUT NUMBER
    );
END LOAN_PKG;
/

CREATE OR REPLACE PACKAGE BODY LOAN_PKG AS
    PROCEDURE CALCULATE_LTV(
        p_loan_amount    IN  NUMBER,
        p_property_value IN  NUMBER,
        p_ltv_ratio      OUT NUMBER
    ) IS
    BEGIN
        IF p_property_value > 0 THEN
            p_ltv_ratio := ROUND((p_loan_amount / p_property_value) * 100, 2);
        ELSE
            p_ltv_ratio := 0;
        END IF;
    END CALCULATE_LTV;
END LOAN_PKG;
/

-- Loan calculation procedures - invoked by LoanDB.jca adapter

-- ============================================================================
-- Package: DECISION_PKG (DecisionDB.runRiskAssessment stored procedure)
-- ============================================================================
CREATE OR REPLACE PACKAGE DECISION_PKG AS
    -- Run automated risk assessment
    -- Called by: DecisionDB.jca - operation="runRiskAssessment"
    -- InteractionSpec: oracle.tip.adapter.db.DBStoredProcedureInteractionSpec
    PROCEDURE RUN_RISK_ASSESSMENT(
        p_loan_id        IN  VARCHAR2,
        p_credit_score   IN  NUMBER,
        p_ltv_ratio      IN  NUMBER,
        p_monthly_income IN  NUMBER,
        p_loan_amount    IN  NUMBER,
        p_risk_score     OUT NUMBER,
        p_recommendation OUT VARCHAR2,
        p_notes          OUT VARCHAR2
    );
END DECISION_PKG;
/

CREATE OR REPLACE PACKAGE BODY DECISION_PKG AS
    PROCEDURE RUN_RISK_ASSESSMENT(
        p_loan_id        IN  VARCHAR2,
        p_credit_score   IN  NUMBER,
        p_ltv_ratio      IN  NUMBER,
        p_monthly_income IN  NUMBER,
        p_loan_amount    IN  NUMBER,
        p_risk_score     OUT NUMBER,
        p_recommendation OUT VARCHAR2,
        p_notes          OUT VARCHAR2
    ) IS
        v_dti_ratio NUMBER;
        v_score NUMBER := 0;
    BEGIN
        -- Calculate DTI (assuming monthly loan payment is ~0.6% of loan amount)
        v_dti_ratio := ((p_loan_amount * 0.006) / p_monthly_income) * 100;

        -- Score calculation based on credit score (0-400 points)
        IF p_credit_score >= 750 THEN
            v_score := v_score + 400;
        ELSIF p_credit_score >= 700 THEN
            v_score := v_score + 300;
        ELSIF p_credit_score >= 650 THEN
            v_score := v_score + 200;
        ELSIF p_credit_score >= 600 THEN
            v_score := v_score + 100;
        END IF;

        -- Score based on LTV (0-300 points)
        IF p_ltv_ratio <= 80 THEN
            v_score := v_score + 300;
        ELSIF p_ltv_ratio <= 90 THEN
            v_score := v_score + 200;
        ELSIF p_ltv_ratio <= 95 THEN
            v_score := v_score + 100;
        END IF;

        -- Score based on DTI (0-300 points)
        IF v_dti_ratio <= 28 THEN
            v_score := v_score + 300;
        ELSIF v_dti_ratio <= 36 THEN
            v_score := v_score + 200;
        ELSIF v_dti_ratio <= 43 THEN
            v_score := v_score + 100;
        END IF;

        p_risk_score := v_score;

        -- Generate recommendation
        IF v_score >= 800 THEN
            p_recommendation := 'APPROVED';
            p_notes := 'Excellent risk profile. Auto-approved.';
        ELSIF v_score >= 600 THEN
            p_recommendation := 'APPROVED';
            p_notes := 'Good risk profile. Approved with standard terms.';
        ELSIF v_score >= 400 THEN
            p_recommendation := 'MANUAL_REVIEW';
            p_notes := 'Moderate risk. Requires manual underwriting review.';
        ELSE
            p_recommendation := 'REJECTED';
            p_notes := 'High risk profile. Does not meet minimum requirements.';
        END IF;

    END RUN_RISK_ASSESSMENT;
END DECISION_PKG;
/

-- Decision/risk procedures - invoked by DecisionDB.jca adapter

-- ============================================================================
-- Trigger: Update UPDATED_AT on LOAN_APPLICATIONS
-- ============================================================================
CREATE OR REPLACE TRIGGER TRG_LOAN_APPS_UPDATED
    BEFORE UPDATE ON LOAN_APPLICATIONS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- Trigger: Update UPDATED_AT on BORROWERS
-- ============================================================================
CREATE OR REPLACE TRIGGER TRG_BORROWERS_UPDATED
    BEFORE UPDATE ON BORROWERS
    FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- Sample Data (for testing)
-- ============================================================================
INSERT INTO BORROWERS (BORROWER_ID, SSN, NAME, CREDIT_SCORE, MONTHLY_INCOME)
VALUES (BORROWER_SEQ.NEXTVAL, '111-22-3333', 'Test Borrower', 720, 8000);

INSERT INTO LOAN_APPLICATIONS (LOAN_ID, BORROWER_ID, LOAN_AMOUNT, PROPERTY_VALUE, PROPERTY_ADDRESS, STATUS)
VALUES ('TEST-LOAN-001', 1, 200000, 300000, '123 Test St, VA 22030', 'APPROVED');

INSERT INTO LOAN_DECISIONS (DECISION_ID, LOAN_ID, DECISION, RISK_SCORE, NOTES)
VALUES ('TEST-DEC-001', 'TEST-LOAN-001', 'APPROVED', 850, 'Test decision - auto approved');

COMMIT;

-- ============================================================================
-- Grant execute on packages to public (for SOA adapter access)
-- ============================================================================
GRANT EXECUTE ON LOAN_PKG TO PUBLIC;
GRANT EXECUTE ON DECISION_PKG TO PUBLIC;

-- ============================================================================
-- Summary of Database Objects for Parser Mapping
-- ============================================================================
/*
TABLE MAPPING TO JCA ADAPTERS:

1. BORROWERS → BorrowerDB.jca
   - DescriptorName: BorrowerDB.Borrower
   - Operations: insertBorrower, selectBorrowerBySSN, updateBorrowerCredit

2. LOAN_APPLICATIONS → LoanDB.jca
   - DescriptorName: LoanDB.LoanApplication
   - Operations: insertLoanApplication, updateLoanApplication, selectLoanById, calculateLTV

3. LOAN_DECISIONS → DecisionDB.jca
   - DescriptorName: DecisionDB.LoanDecision
   - Operations: insertDecision, selectDecisionByLoan, runRiskAssessment

STORED PROCEDURE MAPPING:

1. LOAN_PKG.CALCULATE_LTV → LoanDB.jca / calculateLTV
   - InteractionSpec: oracle.tip.adapter.db.DBStoredProcedureInteractionSpec

2. DECISION_PKG.RUN_RISK_ASSESSMENT → DecisionDB.jca / runRiskAssessment
   - InteractionSpec: oracle.tip.adapter.db.DBStoredProcedureInteractionSpec
*/
